import ExcelJS from "exceljs";
import type { ProjectData } from "./project-schema";
import { CODE_PROFILES } from "@/engines/profiles";
import { computeMaterials } from "@/engines/materials/residential";
import { computeCost } from "@/engines/cost";
import { computeLabor } from "@/engines/labor";

const BRAND = "FF1E3A5F"; // navy
const HEADER_FILL = "FFE8EEF5";
const ROLE_LABELS: Record<string, string> = {
  mason: "Mason",
  laborer: "Laborer",
  carpenter: "Carpenter",
  painter: "Painter",
  electrician: "Electrician",
  plumber: "Plumber",
  engineer: "Engineer",
};

/** Builds a multi-sheet .xlsx (Summary, Materials, Cost BOQ, Labor) for a project. */
export async function buildProjectWorkbook(
  projectName: string,
  data: ProjectData,
): Promise<ExcelJS.Buffer> {
  const materials = computeMaterials(data);
  const cost = computeCost(data);
  const labor = computeLabor(data);
  const profile = CODE_PROFILES[data.codeProfile].label;

  const wb = new ExcelJS.Workbook();
  wb.creator = "Fatalibuilders Construction App";
  wb.created = new Date();

  const titleRow = (ws: ExcelJS.Worksheet, text: string) => {
    ws.mergeCells("A1:E1");
    const c = ws.getCell("A1");
    c.value = text;
    c.font = { bold: true, size: 14, color: { argb: "FFFFFFFF" } };
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BRAND } };
    c.alignment = { vertical: "middle" };
    ws.getRow(1).height = 24;
  };
  const headerRow = (ws: ExcelJS.Worksheet, row: number, cells: string[]) => {
    const r = ws.getRow(row);
    cells.forEach((t, i) => {
      const c = r.getCell(i + 1);
      c.value = t;
      c.font = { bold: true };
      c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEADER_FILL } };
      c.border = { bottom: { style: "thin" } };
    });
  };

  // ---- Summary ----
  const sum = wb.addWorksheet("Summary");
  sum.columns = [{ width: 32 }, { width: 22 }, { width: 14 }, { width: 14 }, { width: 16 }];
  titleRow(sum, "Fatalibuilders Construction App — Project Summary");
  let r = 3;
  const kv = (k: string, v: string | number) => {
    sum.getCell(`A${r}`).value = k;
    sum.getCell(`A${r}`).font = { bold: true };
    sum.getCell(`B${r}`).value = v;
    r++;
  };
  kv("Project", projectName);
  kv("Country", data.country);
  kv("Code profile", profile);
  kv("Floors", data.floors);
  kv("Footprint (m)", `${data.footprintLengthM} × ${data.footprintWidthM}`);
  r++;
  sum.getCell(`A${r}`).value = "Headline results";
  sum.getCell(`A${r}`).font = { bold: true, size: 12 };
  r++;
  kv("Cost — full contract (KES)", cost.grandTotalFull);
  kv("Cost — labour only (KES)", cost.grandTotalLabour);
  kv("Duration (weeks)", labor.calendarWeeks);
  kv("Peak crew", labor.peakCrew);
  kv("Cement (bags)", materials.totals.cementBags);
  kv("Walling blocks", materials.totals.blocks);
  kv("Reinforcement steel (kg)", materials.totals.steelKg);
  r++;
  sum.getCell(`A${r}`).value =
    `Generated by the Fatalibuilders Construction App using the ${profile} profile. ` +
    `Estimating figures for budgeting only — not a tender or fixed quotation. ` +
    `Engineering outputs require review by a licensed engineer.`;
  sum.getCell(`A${r}`).font = { italic: true, size: 9 };
  sum.mergeCells(`A${r}:E${r}`);
  sum.getRow(r).height = 40;
  sum.getCell(`A${r}`).alignment = { wrapText: true, vertical: "top" };

  // ---- Materials ----
  const mat = wb.addWorksheet("Materials");
  mat.columns = [{ width: 40 }, { width: 14 }, { width: 12 }];
  titleRow(mat, "Material Quantities");
  let mr = 3;
  for (const section of materials.sections) {
    mat.getCell(`A${mr}`).value = section.title;
    mat.getCell(`A${mr}`).font = { bold: true, color: { argb: BRAND } };
    mr++;
    headerRow(mat, mr, ["Item", "Quantity", "Unit"]);
    mr++;
    for (const it of section.items) {
      mat.getCell(`A${mr}`).value = it.label;
      mat.getCell(`B${mr}`).value = it.quantity;
      mat.getCell(`C${mr}`).value = it.unit;
      mr++;
    }
    mr++;
  }

  // ---- Cost BOQ ----
  const boq = wb.addWorksheet("Cost BOQ");
  boq.columns = [
    { width: 40 },
    { width: 10 },
    { width: 8 },
    { width: 14 },
    { width: 16 },
  ];
  titleRow(boq, "Bill of Quantities (KES)");
  let br = 3;
  for (const section of cost.sections) {
    boq.getCell(`A${br}`).value = section.title;
    boq.getCell(`A${br}`).font = { bold: true, color: { argb: BRAND } };
    br++;
    headerRow(boq, br, ["Item", "Qty", "Unit", "Rate (full)", "Amount (full)"]);
    br++;
    for (const it of section.items) {
      boq.getCell(`A${br}`).value = it.label;
      boq.getCell(`B${br}`).value = it.quantity;
      boq.getCell(`C${br}`).value = it.unit;
      boq.getCell(`D${br}`).value = it.rateFull;
      boq.getCell(`E${br}`).value = it.amountFull;
      boq.getCell(`D${br}`).numFmt = "#,##0";
      boq.getCell(`E${br}`).numFmt = "#,##0";
      br++;
    }
    boq.getCell(`D${br}`).value = "Subtotal";
    boq.getCell(`D${br}`).font = { bold: true };
    boq.getCell(`E${br}`).value = section.subtotalFull;
    boq.getCell(`E${br}`).font = { bold: true };
    boq.getCell(`E${br}`).numFmt = "#,##0";
    br += 2;
  }
  const totalRow = (label: string, value: number, bold = false) => {
    boq.getCell(`D${br}`).value = label;
    boq.getCell(`E${br}`).value = value;
    boq.getCell(`E${br}`).numFmt = "#,##0";
    if (bold) {
      boq.getCell(`D${br}`).font = { bold: true };
      boq.getCell(`E${br}`).font = { bold: true, size: 12 };
    }
    br++;
  };
  totalRow("Measured works", cost.measuredWorksFull);
  totalRow("Contingency (5%)", cost.contingencyFull);
  totalRow("GRAND TOTAL (full contract)", cost.grandTotalFull, true);
  totalRow("GRAND TOTAL (labour only)", cost.grandTotalLabour, true);

  // ---- Labor ----
  const lab = wb.addWorksheet("Labor Plan");
  lab.columns = [{ width: 30 }, { width: 30 }, { width: 10 }, { width: 16 }];
  titleRow(lab, "Labor & Time Plan");
  let lr = 3;
  lab.getCell(`A${lr}`).value = `Estimated duration: ${labor.calendarWeeks} weeks · Peak crew: ${labor.peakCrew}`;
  lab.getCell(`A${lr}`).font = { bold: true };
  lr += 2;
  headerRow(lab, lr, ["Phase", "Crew", "Days", "Labor cost (KES)"]);
  lr++;
  for (const p of labor.phases) {
    lab.getCell(`A${lr}`).value = p.name;
    lab.getCell(`B${lr}`).value = p.crew
      .map((c) => `${c.count} ${ROLE_LABELS[c.role] ?? c.role}`)
      .join(" + ");
    lab.getCell(`C${lr}`).value = p.durationDays;
    lab.getCell(`D${lr}`).value = p.laborCostKES;
    lab.getCell(`D${lr}`).numFmt = "#,##0";
    lr++;
  }
  lab.getCell(`A${lr}`).value = "Supervision (engineer)";
  lab.getCell(`B${lr}`).value = "1 Engineer, weekly";
  lab.getCell(`C${lr}`).value = labor.supervisionDays;
  lab.getCell(`D${lr}`).value = labor.supervisionDays * labor.dayRates.engineer;
  lab.getCell(`D${lr}`).numFmt = "#,##0";
  lr++;
  lab.getCell(`A${lr}`).value = "Total labor cost";
  lab.getCell(`A${lr}`).font = { bold: true };
  lab.getCell(`D${lr}`).value = labor.totalLaborCostKES;
  lab.getCell(`D${lr}`).numFmt = "#,##0";
  lab.getCell(`D${lr}`).font = { bold: true, size: 12 };

  return wb.xlsx.writeBuffer();
}
