"""Deriv — MetaTrader 5 broker with 24/7 synthetic indices.

Traits that differ from a plain MT5 broker:
  * Synthetic indices (Volatility / Boom / Crash / Step / Jump) trade
    around the clock, weekends included, when every real market is shut.
  * Their symbol names contain SPACES ("Volatility 75 Index") and are used
    verbatim — no suffix is appended.
  * Deriv commonly requires FOK filling; IOC gets rejected on synthetics.

Synthetic prices are generated by Deriv's own engine rather than an
external market, which makes Deriv the venue, the price source and the
counterparty at once. See the README before trading them with real money.
"""

from __future__ import annotations

from .mt5 import MT5Broker


class DerivBroker(MT5Broker):
    broker_name = "Deriv"
    preferred_filling = "FOK"
    symbol_suffix = ""

    @staticmethod
    def is_synthetic(symbol: str) -> bool:
        upper = symbol.upper()
        return any(key in upper for key in
                   ("VOLATILITY", "BOOM", "CRASH", "STEP INDEX", "JUMP"))

    def trades_on_weekends(self, symbol: str) -> bool:
        """Synthetics run 24/7; Deriv's real-market symbols follow normal hours."""
        return self.is_synthetic(symbol)
